import os
from typing import List, Dict
from pydantic import BaseModel
from google.adk.workflow import Workflow, START
from google.adk.agents import LlmAgent


def _load_skill_rules() -> str:
    skill_path = os.path.join(
        os.path.dirname(os.path.dirname(__file__)), 
        ".agents", "skills", "not-a-vibe-coder", "SKILL.md"
    )
    
    if not os.path.exists(skill_path):
        raise FileNotFoundError(
            f"CRITICAL ERROR: Required skill file not found at {skill_path}. "
            "The agent cannot function without this skill."
        )
        
    with open(skill_path, "r") as skill_file:
        return skill_file.read()


class RequirementRequest(BaseModel):
    task: str


class AgentResponse(BaseModel):
    files_to_write: Dict[str, str]
    clarifying_questions: List[str]
    message_to_user: str


requirement_agent = LlmAgent(
    name="requirement_agent",
    model="gemini-2.5-flash",
    instruction=f"""You are the Requirement Agent.
Execute the user's task strictly according to the skill defined below. Do not deviate, summarize, or invent new workflow steps. If there is a conflict, the skill document wins.

<SKILL_DOCUMENT>
{_load_skill_rules()}
</SKILL_DOCUMENT>""",
    output_schema=AgentResponse,
    output_key="requirement_response",
)


def _write_planning_files(files_to_write: Dict[str, str]) -> str:
    if not files_to_write:
        return ""
        
    status_messages = []
    for filename, content in files_to_write.items():
        with open(filename, "w") as file:
            file.write(content)
        status_messages.append(f"✅ Successfully created/updated: `{filename}`")
        
    return "\n".join(status_messages) + "\n"


def _format_clarifying_questions(questions: List[str]) -> str:
    if not questions:
        return ""
    
    formatted_questions = "\n".join([f"- {question}" for question in questions])
    return f"\n### Clarifying Questions\n{formatted_questions}"


def process_agent_response(node_input: dict) -> str:
    response: AgentResponse = node_input.get('requirement_response')
    if not response:
        raise ValueError("No requirements were generated by the agent.")
        
    file_status = _write_planning_files(response.files_to_write)
    questions = _format_clarifying_questions(response.clarifying_questions)
    
    return f"{file_status}\n{response.message_to_user}\n{questions}".strip()


root_agent = Workflow(
    name="never_sleep_code_team_workflow",
    edges=[(START, requirement_agent), (requirement_agent, process_agent_response)],
    description="A workflow that takes a project idea and generates structured planning documents.",
    input_schema=RequirementRequest,
)
